# TODO: #54,#55: ABSTRACT NAME! e.g. LINKQUALITYCONSTANTS
# TODO: more keys
LINK_QUALITY_KEY_LOSS = 'loss'
LINK_QUALITY_VAL_LOSS_NONE = 0
LINK_QUALITY_VAL_LOSS_ALL = 100

LINK_QUALITY_KEY_BANDWIDTH = 'bandwidth'
LINK_QUALITY_KEY_DELAY = 'delay'
LINK_QUALITY_VAL_BANDWIDTH_MODE_802_11_g = "6912K"
LINK_QUALITY_VAL_BANDWIDTH_UNLIMITED = None